# --- CẤU HÌNH HỆ THỐNG CƠ BẢN (KHÔNG BẢO MẬT) ---

spring.config.import=optional:application-secret.properties

# Cổng chạy Server
server.port=${PORT:8080}

jwt.secret=${JWT_SECRET}
# Cấu hình Database (Nếu chạy Local không có mật khẩu thì để ở đây, nếu có mật khẩu thì chuyển sang file Secret)

spring.data.mongodb.uri=${MONGO_URI}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.port=${MAIL_PORT}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

bank.account.number=${BANK_ACCOUNT_NUMBER}
bank.account.name=${BANK_ACCOUNT_NAME}
bank.name=${BANK_NAME}
bank.qr.template=${BANK_TEMPLATE}


spring.cache.caffeine.spec=${CACHE_CAFFEINE}


recaptcha.min-score=${RECAPTCHA_MIN_SCORE}
recaptcha.verify-url=${RECAPTCHA_URL}
recaptcha.secret=${RECAPTCHA_SECRET_KEY}

app.search.meilisearch.enabled=false
meilisearch.url=${MEILISEARCH_URL}
meilisearch.api-key=${MEILI_MASTER_KEY}

ai.api.url=${AI_URL}

google.client-id=${GOOGLE_CLIENT_ID}

# (ĐÃ XÓA TOÀN BỘ CÁC DÒNG CLOUDINARY, MAIL, MEILISEARCH BỊ RỖNG Ở ĐÂY)