# --- CẤU HÌNH HỆ THỐNG CƠ BẢN (KHÔNG BẢO MẬT) ---

# Gọi file secret vào dự án (Chữ optional giúp Java không báo lỗi nếu file này bị thiếu)
spring.config.import=optional:application-secret.properties

# Cổng chạy Server
server.port=${PORT:8080}

jwt.secret=${JWT_SECRET}
# Cấu hình Database (Nếu chạy Local không có mật khẩu thì để ở đây, nếu có mật khẩu thì chuyển sang file Secret)

spring.data.mongodb.uri=${MONGO_URL}
# Các cấu hình hệ thống khác không chứa mật khẩu
spring.cache.caffeine.spec=
bank.qr.template=
recaptcha.min-score=0.5
recaptcha.verify-url=https://www.google.com/recaptcha/api/siteverify

app.search.meilisearch.enabled=false
meilisearch.url=${MEILISEARCH_URL}
meilisearch.api-key=${MEILI_MASTER_KEY}

ai.api.url=${AI_URL}

# (ĐÃ XÓA TOÀN BỘ CÁC DÒNG CLOUDINARY, MAIL, MEILISEARCH BỊ RỖNG Ở ĐÂY)