# --- CẤU HÌNH HỆ THỐNG CƠ BẢN (KHÔNG BẢO MẬT) ---

spring.config.import=optional:application-secret.properties


# Cổng chạy Server
server.port=${PORT:8080}

jwt.secret=${JWT_SECRET_KEY}
# Cấu hình Database (Nếu chạy Local không có mật khẩu thì để ở đây, nếu có mật khẩu thì chuyển sang file Secret)

spring.data.mongodb.uri=${MONGO_URI}

spring.mail.host=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.port=${MAIL_PORT}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

bank.account.number=${BANK_ACCOUNT_NUMBER}
bank.account.name=${BANK_ACCOUNT_NAME}
bank.name=${BANK_NAME}
bank.qr.template=${BANK_TEMPLATE}

spring.cache.type=caffeine
spring.cache.caffeine.spec=${CACHE_CAFFEINE}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

recaptcha.min-score=${RECAPTCHA_MIN_SCORE}
recaptcha.verify-url=${RECAPTCHA_URL}
recaptcha.secret=${RECAPTCHA_SECRET_KEY}

app.search.meilisearch.enabled=true
meilisearch.url=${MEILISEARCH_URL:http://localhost:7700}
meilisearch.api-key=${MEILI_MASTER_KEY:default_key_local}



ai.api.url=${AI_URL}

google.client-id=${GOOGLE_CLIENT_ID}


# (ĐÃ XÓA TOÀN BỘ CÁC DÒNG CLOUDINARY, MAIL, MEILISEARCH BỊ RỖNG Ở ĐÂY)